// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CppWinRT.Builders
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EnumFormattingTemplate : EnumFormattingTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// This file was automatically generated by CppWinRT.Builders\r\n#include <winrt/");
            
            #line 7 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_type.GetNamespace()));
            
            #line default
            #line hidden
            this.Write(".h>\r\n#include <winrt/formatters/helpers.h>\r\n\r\nnamespace winrt::formatters::impl\r\n" +
                    "{\r\n  template<>\r\n  struct traits<");
            
            #line 13 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetCppTypeName(_type)));
            
            #line default
            #line hidden
            this.Write(">\r\n\t{\r\n\t\tusing value_type = ");
            
            #line 15 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetCppTypeName(_type)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tstatic constexpr std::wstring_view name{ L\"");
            
            #line 16 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_type.GetFullName()));
            
            #line default
            #line hidden
            this.Write("\" };\r\n\r\n    using tuple_t = std::pair<std::wstring_view, ");
            
            #line 18 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetCppTypeName(_type)));
            
            #line default
            #line hidden
            this.Write(">;\r\n    inline static constexpr std::array values\r\n\t\t{\r\n");
            
            #line 21 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
 foreach (var value in _type.GetFields()) { 
            
            #line default
            #line hidden
            this.Write("      tuple_t { L\"");
            
            #line 22 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.GetName()));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 22 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetCppTypeName(_type)));
            
            #line default
            #line hidden
            this.Write("::");
            
            #line 22 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.GetName()));
            
            #line default
            #line hidden
            this.Write(" },\r\n");
            
            #line 23 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    };\r\n\t};\r\n}\r\n\r\ntemplate<>\r\nconstexpr std::wstring_view std::formatter<");
            
            #line 29 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetCppTypeName(_type)));
            
            #line default
            #line hidden
            this.Write(", wchar_t>::to_string(const ");
            
            #line 29 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetCppTypeName(_type)));
            
            #line default
            #line hidden
            this.Write(@"& value)
{
    using traits_t = winrt::formatters::impl::traits<winrt::RuntimeComponent1::MyEnum>;
    const auto entry = std::find_if(traits_t::values.begin(), traits_t::values.end(), [&value](const traits_t::tuple_t& entry) { return entry.second == value; });
    if (entry != traits_t::values.end())
    {
      return entry->first;
    }
    return L""Unknown"";
}

template<>
constexpr ");
            
            #line 41 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetCppTypeName(_type)));
            
            #line default
            #line hidden
            this.Write(" std::formatter<");
            
            #line 41 "F:\CppWinRTBuilders\EnumFormattingTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetCppTypeName(_type)));
            
            #line default
            #line hidden
            this.Write(@", wchar_t>::from_string(std::wstring_view value)
{
    using traits_t = winrt::formatters::impl::traits<winrt::RuntimeComponent1::MyEnum>;
		const auto entry = std::find_if(traits_t::values.begin(), traits_t::values.end(), [&value](const traits_t::tuple_t& entry) { return entry.first == value; });
		if (entry != traits_t::values.end())
		{
			return entry->second;
		}
		throw winrt::hresult_invalid_argument{};
}
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class EnumFormattingTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
