// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CppWinRT.OpenApi
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CppWinRTGenerator : CppWinRTGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// This file was automatically generated by CppWinRT.OpenApi\r\n// from the OpenAPI" +
                    " specification at ");
            
            #line 7 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SpecificationUrl));
            
            #line default
            #line hidden
            this.Write("\r\n// (");
            
            #line 8 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OpenApiPath));
            
            #line default
            #line hidden
            this.Write(")\r\n// Do not edit this file directly, as it will be overwritten.\r\n// Using server" +
                    ": ");
            
            #line 10 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ServerDescription));
            
            #line default
            #line hidden
            this.Write(" -> ");
            
            #line 10 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ServerUri));
            
            #line default
            #line hidden
            this.Write(@"

#include <winrt/Windows.Data.Json.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Web.Http.h>
#include <winrt/Windows.Web.Http.Headers.h>
#include <wil/coroutine.h>
#include <format>
#include <array>

// ");
            
            #line 21 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("\r\n// Version ");
            
            #line 22 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nnamespace ");
            
            #line 24 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\nenum class ServerEnvironment\r\n{\r\n  Default = 0,\r\n");
            
            #line 29 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var server in Servers) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 30 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(server.Key.Replace(" ", "_")));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 31 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("};\r\n\r\nstruct ServerConfig\r\n{\r\n  ServerEnvironment environment;\r\n  std::wstring_vi" +
                    "ew uri;\r\n};\r\n\r\nconstexpr std::array ServerConfigList = {\r\n  ServerConfig{ServerE" +
                    "nvironment::Default, L\"");
            
            #line 41 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ServerUri));
            
            #line default
            #line hidden
            this.Write("\"},\r\n");
            
            #line 42 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var server in Servers) { 
            
            #line default
            #line hidden
            this.Write("  ServerConfig{ServerEnvironment::");
            
            #line 43 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(server.Key.Replace(" ", "_")));
            
            #line default
            #line hidden
            this.Write(", L\"");
            
            #line 43 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(server.Value));
            
            #line default
            #line hidden
            this.Write("\"},\r\n");
            
            #line 44 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("};\r\n\r\nstruct Void {\r\n  Void() = default;\r\n  template<typename TIn> Void(TIn&&) {}" +
                    "\r\n};\r\n\r\n");
            
            #line 52 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var security in Security) { 
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(security.Value.GetCppDefinition()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 54 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 56 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var newType in GetGraphOrderedCustomTypes().Where(x => x.Key != "null")) { 
            
            #line default
            #line hidden
            this.Write("\r\nstruct ");
            
            #line 58 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(newType.Value.CppWinRTName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 60 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var property in newType.Value.Members) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 61 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LookupType(property.Schema.JsonName).CppWinRTName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 61 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("{};\r\n");
            
            #line 62 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n  ");
            
            #line 64 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(newType.Value.CppWinRTName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("() = default;\r\n\r\n");
            
            #line 66 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 if (!newType.Value.IsArray) { 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 67 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(newType.Value.CppWinRTName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(const winrt::Windows::Data::Json::JsonObject& json)\r\n  {\r\n");
            
            #line 69 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var property in newType.Value.Members) { 
            
            #line default
            #line hidden
            this.Write("\tif (json.HasKey(L\"");
            
            #line 70 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\"))\r\n\t{\r\n\t\t");
            
            #line 72 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 72 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCppCast(property.Schema.JsonName)));
            
            #line default
            #line hidden
            this.Write("(json.");
            
            #line 72 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(JsonObjectMethod(property)));
            
            #line default
            #line hidden
            this.Write("(L\"");
            
            #line 72 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\"));\r\n\t}\r\n");
            
            #line 74 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  }\r\n");
            
            #line 76 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } else { 
    var elementType = GetArrayElementType(newType.Value);
    var elementTypeCppWinRT = elementType.CppWinRTFullName;
    var getFromJsonMethodName = GetFromJsonMethodName(elementType);

            
            #line default
            #line hidden
            this.Write("  std::vector<");
            
            #line 81 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementTypeCppWinRT));
            
            #line default
            #line hidden
            this.Write("> items;\r\n  ");
            
            #line 82 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(newType.Value.CppWinRTName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(const winrt::Windows::Data::Json::JsonArray& json)\r\n  {\r\n    for (const auto& e " +
                    ": json)\r\n    {\r\n      items.emplace_back(std::move(");
            
            #line 86 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementTypeCppWinRT));
            
            #line default
            #line hidden
            this.Write("{e.");
            
            #line 86 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getFromJsonMethodName));
            
            #line default
            #line hidden
            this.Write("()}));\r\n    }\r\n");
            
            #line 88 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var property in newType.Value.Members) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 89 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = json.");
            
            #line 89 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(JsonObjectMethod(property)));
            
            #line default
            #line hidden
            this.Write("(L\"");
            
            #line 89 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 90 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  }\r\n");
            
            #line 92 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n  winrt::Windows::Data::Json::IJsonValue ToJsonValue() const\r\n  {\r\n");
            
            #line 96 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 if (!newType.Value.IsArray) { 
            
            #line default
            #line hidden
            this.Write("    auto json = winrt::Windows::Data::Json::JsonObject();\r\n");
            
            #line 98 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var property in newType.Value.Members) { 
            
            #line default
            #line hidden
            this.Write("\t\tjson.Insert(L\"");
            
            #line 99 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 99 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateValueMethodName(property.Schema)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 99 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 100 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 101 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } else {
		var elementType = GetArrayElementType(newType.Value);
		var createValueMethodName = CreateValueMethodName(elementType);

            
            #line default
            #line hidden
            this.Write("\t\tauto json = winrt::Windows::Data::Json::JsonArray();\r\n\t\tfor (const auto& e : it" +
                    "ems)\r\n\t\t{\r\n\t\t\tjson.Append(");
            
            #line 108 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(createValueMethodName));
            
            #line default
            #line hidden
            this.Write("(e));\r\n\t\t}\r\n");
            
            #line 110 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\treturn json;\r\n  }\r\n\r\n  static auto ToJsonValue(const ");
            
            #line 114 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(newType.Value.CppWinRTName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("& value)\r\n\t{\r\n\t\treturn value.ToJsonValue();\r\n\t}\r\n};\r\n\r\n");
            
            #line 120 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
namespace details
{
template<typename T>
struct HasSendRequestAsync
{
  template<typename U, typename = decltype(std::declval<U>().SendRequestAsync(std::declval<winrt::Windows::Web::Http::HttpRequestMessage>()))>
  static std::true_type test(int);

  template<typename>
  static std::false_type test(...);

  static constexpr bool value = decltype(test<T>(0))::value;
};

template<typename T>
struct HasClose
{
  template<typename U, typename = decltype(std::declval<U>().Close())>
  static std::true_type test(int);

  template<typename>
  static std::false_type test(...);

  static constexpr bool value = decltype(test<T>(0))::value;
};

template<typename T>
constexpr bool IsHttpClientIsh_v = HasSendRequestAsync<T>::value && HasClose<T>::value;

}

// APIs

");
            
            #line 155 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var path in Paths) { 
var TSecuritySchemaTemplateTypeParam = (path.Security != null && path.Security.Count() > 0) ? $"typename TSecuritySchema = {path.DefaultSecurityCppType}," : string.Empty;

            
            #line default
            #line hidden
            
            #line 158 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.DoxygenComment));
            
            #line default
            #line hidden
            this.Write("\r\ntemplate<typename THttpClient, ");
            
            #line 159 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TSecuritySchemaTemplateTypeParam));
            
            #line default
            #line hidden
            this.Write("ServerEnvironment serverEnvironment = ServerEnvironment::Default>\r\n");
            
            #line 160 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 System.Diagnostics.Debug.WriteLine(path.PathUriTemplate);
            
            #line default
            #line hidden
            this.Write("wil::com_task<");
            
            #line 161 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.ResponseType.CppWinRTFullName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 161 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPathCppName(path)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 161 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCppWinRTParameters(path, true)));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n  constexpr auto serverUri = std::find_if(ServerConfigList.begin(), ServerC" +
                    "onfigList.end(), [](const auto& config) { return config.environment == serverEnv" +
                    "ironment; })->uri;\r\n  auto path = std::format(");
            
            #line 164 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConstructPath(path)));
            
            #line default
            #line hidden
            this.Write(");\r\n  winrt::Windows::Data::Json::JsonObject jsonBody;\r\n");
            
            #line 166 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 if (path.RequestBody != null) { 
            
            #line default
            #line hidden
            
            #line 167 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
   foreach (var property in path.RequestBody.Properties) { 
            
            #line default
            #line hidden
            this.Write("  auto jsonValue_");
            
            #line 168 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 168 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateValueMethodName(property.Schema)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 168 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n  jsonBody.Insert(L\"");
            
            #line 169 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\", jsonValue_");
            
            #line 169 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 170 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
   } 
  } 
            
            #line default
            #line hidden
            this.Write("  auto jsonPayload = jsonBody.Stringify();\r\n\r\n  auto request = winrt::Windows::We" +
                    "b::Http::HttpRequestMessage(winrt::Windows::Web::Http::HttpMethod::");
            
            #line 174 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.Method));
            
            #line default
            #line hidden
            this.Write("(), winrt::Windows::Foundation::Uri(path));\r\n  request.Content(winrt::Windows::We" +
                    "b::Http::HttpStringContent(jsonPayload, winrt::Windows::Storage::Streams::Unicod" +
                    "eEncoding::Utf8, L\"application/json\"));\r\n");
            
            #line 176 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 if (path.Security != null && path.Security.Count() > 0) { 
            
            #line default
            #line hidden
            this.Write("  _security.apply(request, _client);\r\n");
            
            #line 178 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"  auto response = co_await _client.SendRequestAsync(request);
  auto responseContent = co_await response.Content().ReadAsStringAsync();
  if (!response.IsSuccessStatusCode())
  {
    const auto errorJson = winrt::Windows::Data::Json::JsonObject::Parse(responseContent);
	const auto statusCode = static_cast<int32_t>(response.StatusCode());
	const auto hresult = MAKE_HRESULT(SEVERITY_ERROR, FACILITY_HTTP, statusCode);
	throw winrt::hresult_error(hresult, errorJson.GetNamedString(L""message""));
  }

");
            
            #line 189 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 if (path.ResponseType.IsArray) { 
            
            #line default
            #line hidden
            this.Write("  auto responseJson = winrt::Windows::Data::Json::JsonArray::Parse(responseConten" +
                    "t);\r\n");
            
            #line 191 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("  auto responseJson = winrt::Windows::Data::Json::JsonObject::Parse(responseConte" +
                    "nt);\r\n");
            
            #line 193 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
	if (path.ResponseType.JsonName == "null") { 
            
            #line default
            #line hidden
            this.Write("  co_return responseJson;\r\n");
            
            #line 196 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("  // parse the json as ");
            
            #line 197 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.ResponseType.CppWinRTName));
            
            #line default
            #line hidden
            this.Write("\r\n  co_return ");
            
            #line 198 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.ResponseType.CppWinRTFullName));
            
            #line default
            #line hidden
            this.Write("{responseJson};\r\n");
            
            #line 199 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            
            #line 202 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.DoxygenComment));
            
            #line default
            #line hidden
            this.Write("\r\n\r\ntemplate<");
            
            #line 204 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TSecuritySchemaTemplateTypeParam));
            
            #line default
            #line hidden
            this.Write("ServerEnvironment serverEnvironment = ServerEnvironment::Default>\r\nwil::com_task<" +
                    "");
            
            #line 205 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.ResponseType.CppWinRTFullName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 205 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPathCppName(path)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 205 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCppWinRTParameters(path, false)));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n  auto _client = winrt::Windows::Web::Http::HttpClient();\r\n");
            
            #line 208 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 var TSecuritySchemaTemplateParam = (path.Security != null && path.Security.Count() > 0) ? ", TSecuritySchema" : ""; 
            
            #line default
            #line hidden
            this.Write("  auto ret = co_await ");
            
            #line 209 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPathCppName(path)));
            
            #line default
            #line hidden
            this.Write("<decltype(_client)");
            
            #line 209 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TSecuritySchemaTemplateParam));
            
            #line default
            #line hidden
            this.Write(", serverEnvironment>(");
            
            #line 209 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.GetParametersNamesWithHttpClient()));
            
            #line default
            #line hidden
            this.Write(");\r\n  _client.Close();\r\n");
            
            #line 211 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 if (path.ResponseType.CppWinRTName == "Void") { 
            
            #line default
            #line hidden
            this.Write("  UNREFERENCED_PARAMETER(ret);\r\n  co_return Void{};\r\n");
            
            #line 214 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write(" \r\n  co_return ret;\r\n");
            
            #line 216 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            
            #line 219 "C:\Users\asklar\source\repos\CppWinRTBuilderCodeGen\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class CppWinRTGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
