// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CppWinRT.OpenApi
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CppWinRTGenerator : CppWinRTGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// This file was automatically generated by CppWinRT.OpenApi\r\n\r\n#include <winrt/W" +
                    "indows.Data.Json.h>\r\n#include <winrt/Windows.Foundation.h>\r\n\r\n");
            
            #line 11 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var newType in types.Where(x => !x.Value.IsBuiltIn)) { 
            
            #line default
            #line hidden
            this.Write("namespace winrt::OpenApiResponse\r\n{\r\nstruct ");
            
            #line 14 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(newType.Value.CppWinRTName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 16 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var property in newType.Value.Members) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 17 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LookupType(property.Schema.JsonName).CppWinRTName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 17 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("{};\r\n");
            
            #line 18 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 19 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(newType.Value.CppWinRTName));
            
            #line default
            #line hidden
            this.Write("(const winrt::Windows::Data::Json::JsonObject& json)\r\n  {\r\n");
            
            #line 21 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var property in newType.Value.Members) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 22 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = json.");
            
            #line 22 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(JsonObjectMethod(property)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 22 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 23 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  }\r\n};\r\n\r\n");
            
            #line 27 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            
            #line 30 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 foreach (var path in Paths) { 
            
            #line default
            #line hidden
            this.Write("// ");
            
            #line 31 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.PathUriTemplate));
            
            #line default
            #line hidden
            this.Write("\r\n// ");
            
            #line 32 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.Summary));
            
            #line default
            #line hidden
            this.Write("\r\n// ");
            
            #line 33 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.Description));
            
            #line default
            #line hidden
            this.Write("auto ");
            
            #line 33 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 33 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCppWinRTParameters(path)));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n  // implementation\r\n  auto path = std::vformat(");
            
            #line 36 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConstructPath(path)));
            
            #line default
            #line hidden
            this.Write(");\r\n  winrt::Windows::Data::Json::JsonObject jsonBody;\r\n");
            
            #line 38 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 if (path.RequestBody != null) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 39 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
   foreach (var property in path.RequestBody.Properties) { 
            
            #line default
            #line hidden
            this.Write("auto jsonValue_");
            
            #line 39 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = winrt::Windows::Data::Json::JsonValue::");
            
            #line 39 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateValueMethodName(property)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 39 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n  jsonBody.Insert(L\"");
            
            #line 40 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\", jsonValue_");
            
            #line 40 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 41 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
   } 
  } 
            
            #line default
            #line hidden
            this.Write("  auto jsonPayload = jsonBody.Stringify();\r\n\r\n  auto request = winrt::Windows::We" +
                    "b::Http::HttpRequestMessage(winrt::Windows::Web::Http::HttpMethod::");
            
            #line 45 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.Method));
            
            #line default
            #line hidden
            this.Write(@"(), winrt::Windows::Foundation::Uri(path));
  request.Content(winrt::Windows::Web::Http::HttpStringContent(jsonPayload, winrt::Windows::Storage::Streams::UnicodeEncoding::Utf8, L""application/json""));
  auto response = co_await client.SendRequestAsync(request);
  auto responseContent = co_await response.Content().ReadAsStringAsync();
  auto responseJson = winrt::Windows::Data::Json::JsonObject::Parse(responseContent);
  // parse the json as ");
            
            #line 50 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.ResponseType.CppWinRTName));
            
            #line default
            #line hidden
            this.Write("\r\n  return winrt::OpenApiResponse::");
            
            #line 51 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path.ResponseType.CppWinRTName));
            
            #line default
            #line hidden
            this.Write("{responseJson};\r\n}\r\n\r\n");
            
            #line 54 "F:\CppWinRTBuilders\CppWinRT.OpenApi\CppWinRTGenerator.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class CppWinRTGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
